# Build an image using kaniko to get decent caching
steps:
# Tag as the tag & branch if present
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -xc
  - |
    docker pull gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
    if [ -n "$TAG_NAME" ]; then
        docker tag gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
    fi
    if [ -n "$BRANCH_NAME" ]; then
        docker tag gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    fi
    docker rmi gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
images:
- gcr.io/$PROJECT_ID/$REPO_NAME
