# Build an image using kaniko to get decent caching
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
  - --reproducible
  - --cache=true
  - --cache-ttl=1h
# Tag as the tag & branch if present
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -xc
  - |
    docker pull gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
    if [ -n "$TAG_NAME" ]; then
        docker tag gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
    fi
    if [ -n "$BRANCH_NAME" ]; then
        docker tag gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    fi
    docker rmi gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
images:
- gcr.io/$PROJECT_ID/$REPO_NAME
