apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geryon

bases:
- github.com/urcomputeringpal/geryon

# Geryon uses webhooks to "watch" GitHub resources. For the best experience, 
# add an TLS-enabled ingress resource and configure your GitHub App to send 
# webhooks to its URL.
#
resources:
- ingress.yaml

configMapGenerator:
- name: geryon
  envs:
    - .env

secretGenerator:
- name: geryon
  files:
    - private-key.pem