apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kustomize/bases/rbac
- ./kustomize/bases/controller
- ./kustomize/bases/webhooks
images:
- name: geryon
  newName: gcr.io/urcomputeringpal-public/geryon
  newTag: master
