apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployments/geryon.yaml

configMapGenerator:
- name: geryon
  literals:
  - PORT=8080

vars:
- name: PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: geryon
  fieldref:
    fieldpath: data.PORT