apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployments/geryon.yaml

configMapGenerator:
- literals:
  - PORT=8080
  name: geryon

vars:
- fieldref:
    fieldPath: data.PORT
  name: PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: geryon
