apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../bases/rbac
- ../../bases/controller
- ../../bases/webhooks

configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: geryon

secretGenerator:
- files:
  - private-key.pem
  name: geryon

images:
- name: geryon
  newName: gcr.io/urcomputeringpal-public/geryon
