name: master
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0

    - name: docker
      uses: machine-learning-apps/gpr-docker-publish@v1.4
      id: docker
      with:
        IMAGE_NAME: 'master'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: './'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
