name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: short-ref
      id: short-ref
      env:
        REF: ${{ github.ref }}
      run: |
        echo "::set-output name=name::$(echo ${REF} | cut -f 3 -d /)"

    - name: docker
      uses: machine-learning-apps/gpr-docker-publish@v1.4
      id: docker
      with:
        IMAGE_NAME: 'release'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: './'
        TAG: ${{ steps.short-ref.outputs.name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
